---
- name: MariaDB | Deploy and Security Instalation
  hosts: dbservers
  remote_user: root

  roles:
    - roles/db

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  roles:
    - roles/httpd
