---
- name: Wordpress | Remove Apache welcome page
  file: name=/etc/httpd/conf.d/welcome.conf state=absent

- name: Wordpress | Copy wordpress to server
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /tmp/
    creates: /tmp/wordpress/wp-settings.php

- name: Wordpress | Publicando o wordpress no apache
  command: cp -r /tmp/wordpress/. /var/www/html/ creates=/var/www/html/wp-settings.php

- name: Wordpress | Create database wordpress
  mysql_db: name={{ wp_db_name }} state=present

- name: Wordpress | Create wordpress user in database wordpress
  mysql_user: name={{ wp_db_user }} host={{ db_host }} password={{ wp_db_user }} priv={{ wp_db_name }}.*:ALL

- name: Wordpress | Copy file wp-config.php
  copy: src=templates/wp-config.php dest=/var/www/html/wp-config.php

- name: Firewalld | Install python-firewall package
  yum: name=python-firewall state=latest

- name: Firewalld | Allow apache ports
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
   - http
   - https

- name: Firewalld | Recarregando o firewalld
  service: name=firewalld state=restarted

- name: SELinux | Ajustando a configuracao booleana do SELinux
  command: setsebool -P httpd_can_network_connect_db on
