---
- name: MariaDB | Instalando
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: MariaDB | Iniciando o database
  service:
    name: mariadb
    state: started
    enabled: yes

- name: MariaDB | Criando uma nova senha de root
  command: openssl rand -base64 6 creates=/root/.my.cnf
  register: mysql_root_pass
  
- name: MariaDB | Exibe a senha no output do playbook
  debug: 
    msg: "Nova senha de root {{mysql_root_pass.stdout}}"
  when: mysql_root_pass.changed

- name: MariaDB | Removendo acesso anonimo
  mysql_user: name="" host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ ansible_fqdn }}"

- name: MariaDB | Removendo database test
  mysql_db: name=test state=absent

- name: MariaDB | Alterando a senha do root
  mysql_user: name=root host={{item}} password={{mysql_root_pass.stdout}}
  with_items:
   - "{{ansible_fqdn}}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_root_pass.changed

  - name: Publicando .my.cnf no home do root
    template:
      src: templates/client-my-cnf.j2
      dest: /root/.my.cnf
    when: mysql_root_pass.changed
