---
- name: WEB | Add EPEL repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present 

- name: WEB | Install Packages
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - httpd
    - mod_ssl
    - php
    - php-fpm
    - php-gd
    - php-mysql
    - php-mbstring
    - php-mcrypt

- name: WEB | Starting and Enable Apache
  service: 
    name: httpd
    state: started
    enabled: yes

- name: WEB | ServerSignature and ServerTokens
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: '{{ item }}'
  with_items:
    - ServerSignature Off
    - ServerTokens Prod
  notify: restart httpd
